// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// CharacterController is an autogenerated mock type for the CharacterController type
type CharacterController struct {
	mock.Mock
}

// GetCharacterByID provides a mock function with given fields: w, r
func (_m *CharacterController) GetCharacterByID(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetCharacters provides a mock function with given fields: w, r
func (_m *CharacterController) GetCharacters(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetCharactersConcurrently provides a mock function with given fields: w, r
func (_m *CharacterController) GetCharactersConcurrently(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// InsertExternalCharacter provides a mock function with given fields: w, r
func (_m *CharacterController) InsertExternalCharacter(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
